function [ ] = preProcessImage( )
% PreProcess and prepare labelled data for unsupervised deep learning 

I=imread('image.png');
myHistogram1=histogram(I(:,:,1));
K = rangefilt(I);
%figure
%imshow(K);
imwrite(K,'imageRangefilt.png')

[BW,maskedImage]=segmentImage(K);
%figure
%imshow(BW);
imwrite(BW,'imageBW.png')

myTrainImage=~BW;
%figure
%imshow(myTrainImage);
imwrite(myTrainImage,'imageTrainImage.png')


% % Convert to BW
% threshold = graythresh(I);
% BW=im2bw(I,threshold);
% figure
% imshow(BW)
% binaryImage= K >=0 & K<=10; 

% imwrite(BW,'myBW.png')

function [BW,maskedImage] = segmentImage(im)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 25-May-2018
%----------------------------------------------------


% Convert to grayscale
im = rgb2gray(im);

% Initialize segmentation with threshold
mask = im>0;

% Evolve segmentation
BW = activecontour(im, mask, 10, 'Chan-Vese');

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;
end



end
